import assert from 'node:assert/strict'
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { apply } from '../index.js'
import { recommendProfile, scanProject } from '../lib/core.js'
import { discoverCandidates, discoverFromCatalog } from '../lib/discovery.js'

async function tempProject() { return mkdtemp(path.join(os.tmpdir(), 'dsh-smart-profile-')) }
async function modernFixture() {
  const root = await tempProject()
  await writeFile(path.join(root, 'package.json'), JSON.stringify({ dependencies: { next: '15.0.0', react: '19.0.0', pg: '8.0.0' }, devDependencies: { typescript: '5.0.0', '@playwright/test': '1.0.0' } }))
  await writeFile(path.join(root, 'Dockerfile'), 'FROM node:22-alpine\n')
  await mkdir(path.join(root, '.github', 'workflows'), { recursive: true })
  await writeFile(path.join(root, '.github', 'workflows', 'ci.yml'), 'name: CI\n')
  await writeFile(path.join(root, '.env'), 'SECRET=must-not-be-read\n')
  return root
}
test('v0.2 detects modern stack with evidence and confidence', async () => { const root = await modernFixture(); try { const scan = await scanProject(root); assert.equal(scan.schemaVersion, 2); assert.deepEqual(scan.summary.languages, ['TypeScript']); assert.ok(scan.summary.frameworks.includes('Next.js')); assert.ok(scan.summary.databases.includes('PostgreSQL')); assert.ok(scan.summary.infrastructure.includes('Docker')); assert.ok(scan.summary.ci.includes('GitHub Actions')); assert.ok(scan.details.frameworks.find((x) => x.name === 'Next.js').confidenceScore >= 0.9); assert.ok(!scan.evidence.includes('.env')); assert.equal(scan.limits.secretFilesRead, false) } finally { await rm(root, { recursive: true, force: true }) } })
test('v0.2 detects polyglot, cloud and IaC projects', async () => { const root = await tempProject(); try { await writeFile(path.join(root, 'composer.json'), JSON.stringify({ require: { 'laravel/framework': '^12' } })); await writeFile(path.join(root, 'Gemfile'), "gem 'rails'\ngem 'rspec'\n"); await writeFile(path.join(root, 'app.csproj'), '<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><PackageReference Include="xunit" /></ItemGroup></Project>'); await writeFile(path.join(root, 'pubspec.yaml'), 'dependencies:\n  flutter:\n    sdk: flutter\n'); await writeFile(path.join(root, 'main.tf'), 'terraform { required_version = ">= 1.6" }\n'); await mkdir(path.join(root, 'k8s')); await writeFile(path.join(root, 'serverless.yml'), 'provider:\n  name: aws\n'); const scan = await scanProject(root); for (const lang of ['PHP', 'Ruby', '.NET', 'Dart']) assert.ok(scan.summary.languages.includes(lang), lang); for (const fw of ['Laravel', 'Rails', 'ASP.NET Core', 'Flutter']) assert.ok(scan.summary.frameworks.includes(fw), fw); assert.ok(scan.summary.infrastructure.includes('Terraform')); assert.ok(scan.summary.infrastructure.includes('Kubernetes')); assert.ok(scan.summary.cloud.includes('AWS')) } finally { await rm(root, { recursive: true, force: true }) } })
test('recommendProfile expands capabilities for IaC and cloud', async () => { const root = await tempProject(); try { await writeFile(path.join(root, 'main.tf'), 'resource "aws_s3_bucket" "x" {}\n'); await writeFile(path.join(root, 'serverless.yml'), 'provider:\n  name: aws\n'); const ids = recommendProfile(await scanProject(root)).map((x) => x.id); assert.ok(ids.includes('terraform')); assert.ok(ids.includes('cloud')) } finally { await rm(root, { recursive: true, force: true }) } })
test('plugin registers Harness tools and uses session cwd', async () => { const root = await modernFixture(); try { const tools = []; apply({ tools: { register(definition) { tools.push(definition) } } }); assert.deepEqual(tools.map((x) => x.name), ['smart_profile_scan', 'smart_profile_recommend', 'smart_profile_discover']); const result = await tools[0].execute({}, { agent: { session: { header: { cwd: root } } } }); assert.equal(result.root, root); assert.ok(result.summary.frameworks.includes('Next.js')) } finally { await rm(root, { recursive: true, force: true }) } })
test('v0.2 does not treat generic CI/serverless filenames as cloud providers without evidence', async () => { const root = await tempProject(); try { await writeFile(path.join(root, 'serverless.yml'), 'provider:\n  name: google\n'); await writeFile(path.join(root, 'azure-pipelines.yml'), 'trigger: [main]\n'); const scan = await scanProject(root); assert.ok(!scan.summary.cloud.includes('AWS')); assert.ok(!scan.summary.cloud.includes('Azure')); assert.ok(scan.summary.ci.includes('Azure Pipelines')) } finally { await rm(root, { recursive: true, force: true }) } })
test('v0.3 catalog discovery maps packages to capabilities without installing', () => { const recommendations = [{ id: 'browser', searchTerms: ['browser', 'playwright'] }, { id: 'database', searchTerms: ['database', 'postgresql'] }]; const catalog = [{ package: { name: 'dsh-browser-kit', description: 'DeepSeek Harness browser playwright plugin', keywords: ['dsh-plugin', 'playwright'] }, score: { final: 0.8 } }, { package: { name: 'unrelated-browser', description: 'browser helper', keywords: [] }, score: { final: 0.99 } }, { package: { name: 'dsh-db-tools', description: 'deepseek-harness database postgresql tools', keywords: ['dsh-plugin'] }, score: { final: 0.7 } }]; const found = discoverFromCatalog(recommendations, catalog); assert.deepEqual(found.map((x) => x.name).sort(), ['dsh-browser-kit', 'dsh-db-tools']); assert.ok(found.find((x) => x.name === 'dsh-browser-kit').matchedCapabilities.includes('browser')) })
test('v0.3 npm discovery tolerates per-capability network failures', async () => { let calls = 0; const fetchImpl = async () => { calls += 1; if (calls === 2) throw new Error('offline'); return { ok: true, json: async () => ({ objects: [{ package: { name: 'dsh-browser-kit', description: 'DeepSeek Harness browser plugin', keywords: ['dsh-plugin', 'browser'] }, score: { final: 0.8 } }] }) } }; const result = await discoverCandidates([{ id: 'browser', searchTerms: ['browser'] }, { id: 'database', searchTerms: ['database'] }], { fetchImpl }); assert.equal(result.candidates[0].name, 'dsh-browser-kit'); assert.equal(result.errors.length, 1); assert.match(result.note, /No package is installed/) })
