import assert from 'node:assert/strict'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { applySetupPlan, buildSetupPlan, selectCandidates } from '../lib/setup.js'
const healthy = (name, capability, score = 90) => ({ name, version: '1.0.0', score, recommendation: 'preferred', matchedCapabilities: [capability], matchedTerms: [capability], riskFlags: [], metadata: { dsh: { bundle: { patch: './cordis.patch.yml' } }, dependencies: [], optionalDependencies: [], peerDependencies: {}, scripts: {} } })
test('v1.0 candidate selection rejects risky/low-score packages', () => { const result = selectCandidates([{ id: 'browser', title: 'Browser' }, { id: 'database', title: 'Database' }], [healthy('dsh-browser-good', 'browser', 88), { ...healthy('dsh-db-risky', 'database', 95), recommendation: 'review-required', riskFlags: ['lifecycle-scripts:postinstall'] }], { minScore: 70 }); assert.deepEqual(result.selected.map((x) => x.candidate.name), ['dsh-browser-good']); assert.equal(result.unresolved[0].capability, 'database') })
test('v1.0 setup preview composes task, discovery, scoring and exact install plans without writes', async () => { const root = await mkdtemp(path.join(os.tmpdir(), 'dsh-smart-profile-setup-')); try { await writeFile(path.join(root, 'package.json'), JSON.stringify({ dependencies: { react: '19.0.0' }, devDependencies: { typescript: '5.0.0' } })); const discoverFn = async (recommendations) => ({ source: 'fixture', queriedCapabilities: recommendations.map((x) => x.id), candidates: [], errors: [] }); const scoreFn = async () => ({ inspected: 1, candidates: [healthy('dsh-browser-good', 'browser')] }); const plan = await buildSetupPlan(root, { task: 'fix frontend UI', discoverFn, scoreFn }); assert.ok(plan.composition.selected.some((x) => x.id === 'browser')); assert.equal(plan.installs[0].candidate.name, 'dsh-browser-good'); assert.ok(plan.installs[0].plan.commands.verify[1].includes('--dump-config')); assert.equal(plan.writeGate.requiresApprovalFlag, true) } finally { await rm(root, { recursive: true, force: true }) } })
test('v1.0 apply requires approval and does not invoke runner during preview', async () => { let calls = 0; const plan = { installs: [{ candidate: healthy('dsh-browser-good', 'browser'), covers: ['browser'] }], profile: 'web', dshSpec: '@deepseek-ai/dsh@next', unresolved: [] }; const result = await applySetupPlan(plan, { runner: async () => { calls += 1; return { code: 0, stdout: '' } } }); assert.equal(result.status, 'approval-required'); assert.equal(calls, 0) })
test('v1.0 successful setup verifies each install', async () => { const installed = new Set(); const runner = async (_command, args) => { if (args.includes('--dump-config')) return { code: 0, stdout: [...installed].join('\n'), stderr: '' }; if (args.includes('add')) { const spec = args.at(-1); installed.add(spec.replace(/@\d.*$/, '')); return { code: 0, stdout: '', stderr: '' } } if (args.includes('remove')) { installed.delete(args.at(-1)); return { code: 0, stdout: '', stderr: '' } } return { code: 0, stdout: '', stderr: '' } }; const plan = { installs: [{ candidate: healthy('dsh-browser-good', 'browser'), covers: ['browser'] }, { candidate: healthy('dsh-db-good', 'database'), covers: ['database'] }], profile: 'web', dshSpec: '@deepseek-ai/dsh@next', unresolved: [], compatibility: { status: 'ci-target' } }; const result = await applySetupPlan(plan, { approved: true, runner }); assert.equal(result.status, 'configured'); assert.deepEqual([...installed].sort(), ['dsh-browser-good', 'dsh-db-good']) })
test('v1.0 failure rolls back plugins installed earlier in the same setup run', async () => { const installed = new Set(); const runner = async (_command, args) => { if (args.includes('--dump-config')) return { code: 0, stdout: [...installed].join('\n'), stderr: '' }; if (args.includes('add')) { const spec = args.at(-1), name = spec.replace(/@\d.*$/, ''); if (name === 'dsh-db-bad') return { code: 1, stdout: '', stderr: 'install failed' }; installed.add(name); return { code: 0, stdout: '', stderr: '' } if (args.includes('remove')) { installed.delete(args.at(-1)); return { code: 0, stdout: '', stderr: '' } } return { code: 0, stdout: '', stderr: '' } }; const plan = { installs: [{ candidate: healthy('dsh-browser-good', 'browser'), covers: ['browser'] }, { candidate: healthy('dsh-db-bad', 'database'), covers: ['database'] }], profile: 'web', dshSpec: '@deepseek-ai/dsh@next', unresolved: [] }; const result = await applySetupPlan(plan, { approved: true, runner }); assert.equal(result.status, 'failed-rolled-back'); assert.equal(installed.size, 0); assert.ok(result.rollback.some((x) => x.candidate === 'dsh-browser-good')) })
test('v1.0 does not remove a plugin that was already present before setup', async () => { const installed = new Set(['dsh-browser-good']); let addCalls = 0, removeCalls = 0; const runner = async (_command, args) => { if (args.includes('--dump-config')) return { code: 0, stdout: [...installed].join('\n'), stderr: '' }; if (args.includes('add')) { addCalls += 1; return { code: 0, stdout: '', stderr: '' } if (args.includes('remove')) { removeCalls += 1; return { code: 0, stdout: '', stderr: '' } return { code: 0, stdout: '', stderr: '' } }; const plan = { installs: [{ candidate: healthy('dsh-browser-good', 'browser'), covers: ['browser'] }], profile: 'web', dshSpec: '@deepseek-ai/dsh@next', unresolved: [], compatibility: {} }; const result = await applySetupPlan(plan, { approved: true, runner }); assert.equal(result.status, 'configured'); assert.equal(addCalls, 0); assert.equal(removeCalls, 0) })
