import http from 'node:http'
import path from 'node:path'
import { recommendProfile, scanProject } from './core.js'
import { composeTaskProfile } from './compose.js'

const LOOPBACK = new Set(['127.0.0.1', 'localhost', '::1'])
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char])

export async function buildDashboardData(root = process.cwd(), task = '') {
  const scan = await scanProject(path.resolve(root))
  const recommendations = recommendProfile(scan)
  return { generatedAt: new Date().toISOString(), scan, recommendations, composition: task.trim() ? composeTaskProfile(scan, recommendations, task) : null }
}
function chips(items) { if (!items?.length) return '<span class="muted">none detected</span>'; return items.map((item) => `<span class="chip">${esc(item)}</span>`).join('') }
export function renderDashboard(data) {
  const scan = data.scan ?? { root: '', summary: {} }, composition = data.composition, selected = new Set((composition?.selected ?? []).map((x) => x.id))
  const recommendationCards = (data.recommendations ?? []).map((item) => `<article class="card ${selected.has(item.id) ? 'selected' : ''}"><div class="row"><strong>${esc(item.title)}</strong><span class="priority">${esc(item.priority)}</span></div><code>${esc(item.id)}</code><p>${esc(item.reason)}</p>${composition ? `<small>${selected.has(item.id) ? `Selected: ${esc(composition.selected.find((x) => x.id === item.id)?.taskReason)}` : 'Excluded for this task'}</small>` : ''}</article>`).join('')
  const summary = scan.summary ?? {}
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>dsh-smart-profile</title><style>:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#172033;background:#f6f7fb}body{margin:0}.wrap{max-width:1100px;margin:auto;padding:32px 20px 60px}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.badge,.chip,.priority{display:inline-block;border:1px solid #d7dbea;border-radius:999px;padding:5px 9px;margin:3px;font-size:12px;background:white}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.panel,.card{background:white;border:1px solid #e1e4ee;border-radius:14px;padding:16px;box-shadow:0 2px 8px #1720330d}.card.selected{outline:2px solid #4b67ff}.row{display:flex;justify-content:space-between;gap:12px}.muted,small{color:#687086}code{font-size:12px;color:#4f5b76}form{display:flex;gap:8px;margin:22px 0}input{flex:1;border:1px solid #ccd2e3;border-radius:10px;padding:12px}button{border:0;border-radius:10px;padding:12px 16px;background:#25314d;color:white;cursor:pointer}h1{margin:0 0 8px}h2{margin-top:28px}.path{word-break:break-all}.warning{background:#fff9e8;border:1px solid #f1d887;padding:12px;border-radius:12px;margin:16px 0}</style></head><body><main class="wrap"><header><div><h1>dsh-smart-profile</h1><p class="muted">Project-aware DeepSeek Harness capability profile</p><p class="path"><code>${esc(scan.root)}</code></p></div><span class="badge">read-only dashboard</span></header><div class="warning">This web UI does not install, remove, or execute third-party plugins. Write operations remain CLI-only with explicit approval.</div><form method="GET" action="/"><input name="task" value="${esc(composition?.task ?? '')}" placeholder="Optional task, e.g. Fix the frontend Playwright test"><button type="submit">Compose</button></form><section class="panel"><h3>Detected stack</h3>${Object.entries(summary).map(([key, values]) => `<div><strong>${esc(key)}</strong><div>${chips(values)}</div></div>`).join('')}</section><h2>${composition ? 'Task-scoped capabilities' : 'Recommended capabilities'}</h2><div class="grid">${recommendationCards || '<p class="muted">No recommendations.</p>'}</div>${composition ? `<section class="panel" style="margin-top:16px"><strong>Task</strong><p>${esc(composition.task)}</p><small>${esc(composition.note)}</small></section>` : ''}<footer><p class="muted">Generated ${esc(data.generatedAt ?? '')}</p></footer></main></body></html>`
}
function json(res, status, body) { const payload = JSON.stringify(body, null, 2); res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'content-length': Buffer.byteLength(payload), 'cache-control': 'no-store' }); res.end(payload) }
export async function startDashboard({ root = process.cwd(), host = '127.0.0.1', port = 4173, allowRemote = false } = {}) {
  if (!allowRemote && !LOOPBACK.has(host)) throw new Error(`Refusing to bind dashboard to non-loopback host ${host}. Pass allowRemote only if you understand the exposure.`)
  const resolvedRoot = path.resolve(root)
  const server = http.createServer(async (req, res) => { try { const url = new URL(req.url ?? '/', `http://${host}`), task = url.searchParams.get('task') ?? ''; if (url.pathname === '/api/profile') return json(res, 200, await buildDashboardData(resolvedRoot, task)); if (url.pathname !== '/') return json(res, 404, { error: 'not found' }); const html = renderDashboard(await buildDashboardData(resolvedRoot, task)); res.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'content-length': Buffer.byteLength(html), 'cache-control': 'no-store', 'x-content-type-options': 'nosniff', 'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'" }); res.end(html) } catch (error) { json(res, 500, { error: error.message }) } })
  await new Promise((resolve, reject) => { server.once('error', reject); server.listen(port, host, resolve) })
  const address = server.address(), actualPort = typeof address === 'object' && address ? address.port : port
  return { server, host, port: actualPort, url: `http://${host.includes(':') ? `[${host}]` : host}:${actualPort}` }
}
